language: c
sudo: false
dist: xenial
services:
    - xvfb
env:
    global: PYTHON_VERSION=3.7
            CONDA_DEPENDENCIES="numpy scipy matplotlib pyqt>=5.9 coverage pytest pytest-cov flake8 pygments traits traitsui pyface"
            PIP_DEPENDENCIES="codecov pytest-sugar pytest-faulthandler nibabel imageio imageio-ffmpeg"
            DISPLAY=:99.0
            SUBJECTS_DIR=~/subjects

matrix:
    include:
        # Full
        - os: linux
          addons:
            apt:
              packages:
                - mencoder

        # 2.7, no mencoder
        - os: linux
          env: PYTHON_VERSION=2.7
               CONDA_DEPENDENCIES="numpy scipy matplotlib coverage pytest pytest-cov flake8 mayavi"
               PIP_DEPENDENCIES="codecov pytest-sugar faulthandler pytest-faulthandler nibabel imageio"

        # OSX
        - os: osx

# Setup anaconda
before_install:
    # Rvm overrides cd with a function so that it can hook into it to run
    # some scripts, see https://github.com/travis-ci/travis-ci/issues/8703
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        unset -f cd;
      fi;
    - git clone https://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - if [ "$PYTHON_VERSION" != "2.7" ]; then
        pip install vtk;
        pip install mayavi;
      fi;
    - mkdir -p $SUBJECTS_DIR
    - pip install "https://api.github.com/repos/mne-tools/mne-python/zipball/master"
    - python -c "import mne; mne.datasets.fetch_fsaverage(verbose=True)"

install:
    - python setup.py build
    - python setup.py install
    - SRC_DIR=$(pwd)

script:
    - cd ${SRC_DIR}
    - pytest surfer --cov=surfer -v
    - make flake

after_success:
    - codecov
